### ISSUE TITLE
audio none: can not record audio.

### ISSUE THREAD

**Issue by Zenkyou** [AudDMusic/audd-chrome-extension#6]
It can detect if there audio playing or not, but can't record audio at all. All attempts **in any site** gives the message "_audio none: can not record audio_.".

Using Chrome **80.0.3987.132**  whic is the most updated Chrome version disponible **TODAY _(12/03/2020)_ THE DAY IM OPENING THIS THREAD** on a Windows 7 x64.

**Comment by AudD-music** [comment]
We aware of the issue but we don't know what's causing it :(

We're using the latest Chrome version on Win10, and it's working as expected. It's possible that you need to update Windows, but we aren't completely sure.

If someone knows how to fix this, contributions are welcomed
