### ISSUE TITLE
[Suggestion] Porting to Mozilla Firefox?

### ISSUE THREAD

**Issue by DoraTheExploder** [AudDMusic/audd-chrome-extension#7]
I just wanted to see what you think about porting the extension to Firefox. Using the WebExtension API it should be pretty simple to do, so far as I can tell. Let me know what you think of this and, if you're okay with it, I'll take a look at doing so.

**Comment by Mihonarium** [comment]
@DoraTheExploder that would be great! We're totally okay with it.

**Comment by BancarelValentin** [comment]
@DoraTheExploder do ou keep plan on giving it a try ?

**Comment by DoraTheExploder** [comment]
> @DoraTheExploder do you keep plan on giving it a try ?

Nah, I messed with it a little bit but couldn't quite get it to work fully. It's all yours if you want it.

**Comment by Mihonarium** [comment]
If any assistance from our side would be helpful, let me know!

**Comment by DoraTheExploder** [comment]
> If any assistance from our side would be helpful, let me know!

Thanks for the offer, if I recall correctly it was due to the method by which I was trying to port it not being fully compatible with the full feature set. It's been quite a while and I'm unfortunately too busy at work these days. :(

**Comment by iTrooz** [comment]
The extension seem to have been ported: https://github.com/AudDMusic/firefox-extension
