### ISSUE TITLE
Not working just searches forever!

### ISSUE THREAD

**Issue by JReverse** [AudDMusic/audd-chrome-extension#9]
Not working just searches forever!

**Comment by Mihonarium** [comment]
Thanks for reaching out! What's your OS and browser versions?

**Comment by JReverse** [comment]
![image](https://user-images.githubusercontent.com/40630518/129029000-15c87eab-5a94-464c-8d17-afd59da3f966.png)

![image](https://user-images.githubusercontent.com/40630518/129029060-302d6bac-eb3f-432e-a10a-ad57d42da4e2.png)

**Comment by Mihonarium** [comment]
We aren’t able to reproduce it. It’s probably  something soundcards something OS something APIs something; no idea what might help there and not obvious how to debug, sorry
